name: UpdateConfigs
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  UpdateConfigs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        working-directory: ./core-parser-ts
        run: bun install

      - name: Run Collector
        working-directory: ./core-parser-ts
        run: bun index.ts

      - name: Commit and Push
        run: |
          git config --global user.name "Blondie-AI"
          git config --global user.email "blondie@ai.com"
          git add core-parser-ts/category/*.txt
          git commit -m "üë±‚Äç‚ôÄÔ∏è Auto-update: TS Configs collected" || exit 0
          git push
